### PR TITLE
connect to stellar-core on port 8080

### PR DESCRIPTION
**Pull request by FredericHeem**

### CODE REVIEW

**Comment by nullstyle** [comment]
@FredericHeem could you explain why you chose 8080?  The new default http port for stellar-core is 11626

**Comment by FredericHeem** [comment]
Jed has changed the port in the file https://github.com/stellar/stellar-core/blob/master/docs/stellar-core_standalone.cfg and choose 8080. I don't mind of the value of the port, as long as stellar-core and horizon are using the same

**Comment by nullstyle** [comment]
kk, I'm going to close this.  I prefer that we use the default port unless we've got a solid reason not to.

**Comment by FredericHeem** [comment]
Do you mind to change the new default port to 11626 ?

**Pull request closed without merging**
